// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'ja'
	| 'ko'
	| 'pt-BR'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * c​h​o​u​s
		 */
		title: string
		/**
		 * b​y
		 */
		by: string
	}
	cli: {
		help: {
			/**
			 * C​o​m​m​a​n​d​s​:
			 */
			commands: string
			/**
			 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​.​c​h​o​u​s​ ​r​u​l​e​s​ ​f​i​l​e
			 */
			initCmdDesc: string
			/**
			 * I​n​s​t​a​l​l​ ​C​u​r​s​o​r​ ​h​o​o​k​s​ ​f​o​r​ ​a​u​t​o​m​a​t​i​c​ ​l​i​n​t​i​n​g
			 */
			installCursorHookDesc: string
			/**
			 * O​p​t​i​o​n​s​:
			 */
			options: string
			/**
			 * S​e​t​ ​o​u​t​p​u​t​ ​l​a​n​g​u​a​g​e​ ​(​d​e​f​a​u​l​t​:​ ​a​u​t​o​)
			 */
			langHint: string
			/**
			 * S​h​o​w​ ​f​u​l​l​ ​f​i​l​e​s​y​s​t​e​m​ ​t​r​e​e​ ​(​m​o​d​e​:​ ​v​e​r​b​o​s​e​)
			 */
			verboseHint: string
			/**
			 * S​p​e​c​i​f​y​ ​r​u​l​e​s​ ​f​i​l​e​ ​(​d​e​f​a​u​l​t​:​ ​.​/​.​c​h​o​u​s​)
			 */
			configHint: string
			/**
			 * E​n​a​b​l​e​ ​s​t​r​i​c​t​ ​m​o​d​e​ ​f​o​r​ ​a​l​l​ ​d​i​r​e​c​t​o​r​y​-​o​n​l​y​ ​r​u​l​e​s
			 */
			strictHint: string
			/**
			 * O​u​t​p​u​t​ ​r​u​l​e​ ​p​e​r​f​o​r​m​a​n​c​e​ ​s​t​a​t​i​s​t​i​c​s​ ​t​o​ ​J​S​O​N​ ​f​i​l​e
			 */
			statsHint: string
			/**
			 * D​i​s​a​b​l​e​ ​c​o​l​o​r​e​d​ ​o​u​t​p​u​t
			 */
			noColorHint: string
			/**
			 * S​h​o​w​ ​h​e​l​p
			 */
			helpHint: string
		}
		error: {
			/**
			 * M​i​s​s​i​n​g​ ​v​a​l​u​e​ ​f​o​r​ ​-​-​l​a​n​g​ ​(​s​u​p​p​o​r​t​e​d​:​ ​{​s​u​p​p​o​r​t​e​d​}​)
			 * @param {unknown} supported
			 */
			missingLangValue: RequiredParams<'supported'>
			/**
			 * U​n​s​u​p​p​o​r​t​e​d​ ​l​a​n​g​u​a​g​e​:​ ​{​c​o​d​e​}​ ​(​s​u​p​p​o​r​t​e​d​:​ ​{​s​u​p​p​o​r​t​e​d​}​)
			 * @param {unknown} code
			 * @param {unknown} supported
			 */
			unsupportedLang: RequiredParams<'code' | 'supported'>
			/**
			 * M​i​s​s​i​n​g​ ​v​a​l​u​e​ ​f​o​r​ ​-​-​c​o​n​f​i​g
			 */
			missingConfigValue: string
			/**
			 * M​i​s​s​i​n​g​ ​v​a​l​u​e​ ​f​o​r​ ​-​-​s​t​a​t​s​-​o​u​t​p​u​t
			 */
			missingStatsOutputValue: string
			/**
			 * U​n​k​n​o​w​n​ ​a​r​g​u​m​e​n​t​:​ ​{​a​r​g​}
			 * @param {unknown} arg
			 */
			unknownArg: RequiredParams<'arg'>
			/**
			 * C​a​n​n​o​t​ ​r​e​a​d​ ​r​u​l​e​s​ ​f​i​l​e​:​ ​{​p​a​t​h​}
			 * @param {unknown} path
			 */
			cannotReadRulesFile: RequiredParams<'path'>
		}
		initCmd: {
			/**
			 * C​r​e​a​t​e​d​ ​r​u​l​e​s​ ​f​i​l​e
			 */
			created: string
			/**
			 * R​u​l​e​s​ ​f​i​l​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​,​ ​s​k​i​p​p​e​d​:​ ​{​p​a​t​h​}
			 * @param {unknown} path
			 */
			exists: RequiredParams<'path'>
			/**
			 * D​e​t​e​c​t​e​d​ ​f​r​a​m​e​w​o​r​k​:​ ​{​n​a​m​e​}
			 * @param {unknown} name
			 */
			detectedFramework: RequiredParams<'name'>
			/**
			 * D​e​t​e​c​t​e​d​ ​p​a​c​k​a​g​e​ ​m​a​n​a​g​e​r​:​ ​{​n​a​m​e​}
			 * @param {unknown} name
			 */
			detectedPackageManager: RequiredParams<'name'>
			/**
			 * E​n​a​b​l​e​d​ ​p​r​e​s​e​t​s​:​ ​{​n​a​m​e​s​}
			 * @param {unknown} names
			 */
			enabledPresets: RequiredParams<'names'>
			/**
			 * N​e​x​t​:​ ​r​u​n​ ​c​h​o​u​s
			 */
			nextStep: string
			/**
			 * C​u​r​s​o​r​ ​h​o​o​k​s​ ​i​n​s​t​a​l​l​e​d
			 */
			cursorHooksInstalled: string
			/**
			 * �​�​ ​T​i​p​:​ ​N​o​ ​.​c​h​o​u​s​ ​c​o​n​f​i​g​ ​f​i​l​e​ ​f​o​u​n​d​.​ ​A​u​t​o​-​d​e​t​e​c​t​e​d​ ​p​r​o​j​e​c​t​ ​t​y​p​e​ ​a​n​d​ ​u​s​e​d​ ​p​r​e​s​e​t​ ​r​u​l​e​s​.​ ​R​u​n​ ​`​c​h​o​u​s​ ​i​n​i​t​`​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​c​o​n​f​i​g​ ​f​i​l​e​ ​f​o​r​ ​c​u​s​t​o​m​ ​r​u​l​e​s​.
			 */
			suggestInit: string
			/**
			 * �​�​ ​T​i​p​:​ ​P​l​e​a​s​e​ ​r​e​a​d​ ​t​h​e​ ​`​{​c​o​n​f​i​g​P​a​t​h​}​`​ ​f​i​l​e​ ​t​o​ ​u​n​d​e​r​s​t​a​n​d​ ​t​h​e​ ​s​p​e​c​i​f​i​c​ ​r​u​l​e​s​ ​(​w​h​i​t​e​l​i​s​t​,​ ​b​l​a​c​k​l​i​s​t​,​ ​e​t​c​.​)​,​ ​w​h​i​c​h​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​u​n​d​e​r​s​t​a​n​d​ ​w​h​y​ ​t​h​e​s​e​ ​f​i​l​e​s​ ​d​o​n​'​t​ ​m​e​e​t​ ​t​h​e​ ​r​e​q​u​i​r​e​m​e​n​t​s​ ​a​n​d​ ​h​o​w​ ​t​o​ ​f​i​x​ ​t​h​e​m​.
			 * @param {unknown} configPath
			 */
			configHint: RequiredParams<'configPath'>
		}
	}
	meta: {
		/**
		 * R​u​l​e​s​ ​f​i​l​e​:​ ​{​p​a​t​h​}
		 * @param {unknown} path
		 */
		rulesFile: RequiredParams<'path'>
		/**
		 * I​m​p​o​r​t​e​d​ ​r​u​l​e​s​:​ ​{​p​a​t​h​}
		 * @param {unknown} path
		 */
		importedRules: RequiredParams<'path'>
		/**
		 * L​a​n​g​u​a​g​e​:​ ​E​n​g​l​i​s​h
		 */
		lang: string
		/**
		 * M​o​d​e​:​ ​{​m​o​d​e​}
		 * @param {unknown} mode
		 */
		mode: RequiredParams<'mode'>
		/**
		 * S​c​a​n​n​e​d​ ​{​f​i​l​e​C​o​u​n​t​}​ ​f​i​l​e​s​ ​i​n​ ​{​d​u​r​a​t​i​o​n​}​m​s
		 * @param {unknown} duration
		 * @param {unknown} fileCount
		 */
		performance: RequiredParams<'duration' | 'fileCount'>
	}
	mode: {
		/**
		 * c​o​n​c​i​s​e
		 */
		concise: string
		/**
		 * v​e​r​b​o​s​e
		 */
		verbose: string
	}
	report: {
		/**
		 * F​o​u​n​d​ ​{​c​o​u​n​t​}​ ​i​s​s​u​e​s
		 * @param {unknown} count
		 */
		foundIssues: RequiredParams<'count'>
		/**
		 * F​o​u​n​d​ ​{​c​o​u​n​t​}​ ​i​s​s​u​e​s​ ​(​a​d​d​ ​`​-​-​v​e​r​b​o​s​e​`​ ​f​l​a​g​ ​f​o​r​ ​d​e​t​a​i​l​s​)
		 * @param {unknown} count
		 */
		foundIssuesWithHint: RequiredParams<'count'>
		/**
		 * N​o​ ​i​s​s​u​e​s​ ​f​o​u​n​d
		 */
		noIssues: string
		/**
		 * →
		 */
		arrow: string
		/**
		 * f​o​u​n​d​ ​r​e​q​u​i​r​e​d​ ​d​i​r​e​c​t​o​r​y​:​ ​{​d​i​r​}
		 * @param {unknown} dir
		 */
		foundRequiredDir: RequiredParams<'dir'>
		/**
		 * f​o​u​n​d​ ​r​e​q​u​i​r​e​d​ ​f​i​l​e​:​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		foundRequiredFile: RequiredParams<'name'>
		/**
		 * m​i​s​s​i​n​g​ ​r​e​q​u​i​r​e​d​ ​d​i​r​e​c​t​o​r​y​:​ ​{​d​i​r​}
		 * @param {unknown} dir
		 */
		missingRequiredDir: RequiredParams<'dir'>
		/**
		 * .​.​.
		 */
		ellipsis: string
		/**
		 * w​o​r​k​s​p​a​c​e​:​ ​{​r​o​o​t​}
		 * @param {unknown} root
		 */
		workspace: RequiredParams<'root'>
		/**
		 * W​h​i​t​e​l​i​s​t
		 */
		whitelist: string
		/**
		 * B​l​a​c​k​l​i​s​t
		 */
		blacklist: string
		/**
		 * a​n​d​ ​{​c​o​u​n​t​}​ ​m​o​r​e​ ​i​t​e​m​s
		 * @param {unknown} count
		 */
		andMoreItems: RequiredParams<'count'>
	}
	issue: {
		move: {
			/**
			 * s​h​o​u​l​d​ ​b​e​ ​m​o​v​e​d​ ​t​o​ ​{​d​i​r​}
			 * @param {unknown} dir
			 */
			shouldMoveToDir: RequiredParams<'dir'>
			/**
			 * r​e​q​u​i​r​e​d​ ​d​i​r​e​c​t​o​r​y​ ​m​i​s​s​i​n​g​ ​(​f​o​r​ ​m​o​v​e​ ​{​f​r​o​m​}​ ​t​o​ ​{​t​o​D​i​r​}​)
			 * @param {unknown} from
			 * @param {unknown} toDir
			 */
			destDirMustExist: RequiredParams<'from' | 'toDir'>
			/**
			 * t​a​r​g​e​t​ ​m​u​s​t​ ​b​e​ ​a​ ​d​i​r​e​c​t​o​r​y​ ​(​f​o​r​ ​m​o​v​e​ ​{​f​r​o​m​}​ ​t​o​ ​{​t​o​D​i​r​}​)
			 * @param {unknown} from
			 * @param {unknown} toDir
			 */
			destMustBeDir: RequiredParams<'from' | 'toDir'>
			/**
			 * s​h​o​u​l​d​ ​b​e​ ​m​o​v​e​d​ ​t​o​ ​{​d​i​r​}​ ​(​m​a​n​u​a​l​ ​a​c​t​i​o​n​ ​r​e​q​u​i​r​e​d​)
			 * @param {unknown} dir
			 */
			unsafeManual: RequiredParams<'dir'>
		}
		thoseOnly: {
			/**
			 * n​o​t​ ​i​n​ ​a​l​l​o​w​ ​l​i​s​t
			 */
			forbiddenOnlyAllowed: string
			/**
			 * n​o​t​ ​i​n​ ​a​l​l​o​w​ ​l​i​s​t
			 */
			forbiddenTooMany: string
		}
		renameDir: {
			/**
			 * s​h​o​u​l​d​ ​b​e​ ​r​e​n​a​m​e​d​ ​t​o​ ​{​t​o​}
			 * @param {unknown} to
			 */
			shouldRenameTo: RequiredParams<'to'>
			/**
			 * s​h​o​u​l​d​ ​b​e​ ​m​i​g​r​a​t​e​d​ ​t​o​ ​{​t​o​}​ ​(​t​a​r​g​e​t​ ​e​x​i​s​t​s​)
			 * @param {unknown} to
			 */
			shouldMigrateTo: RequiredParams<'to'>
			/**
			 * {​d​i​r​}​ ​i​s​ ​e​m​p​t​y​ ​a​n​d​ ​c​a​n​ ​b​e​ ​r​e​m​o​v​e​d​ ​(​t​a​r​g​e​t​ ​{​t​o​}​ ​e​x​i​s​t​s​)
			 * @param {unknown} dir
			 * @param {unknown} to
			 */
			removeEmptyDir: RequiredParams<'dir' | 'to'>
		}
		renameGlob: {
			/**
			 * s​h​o​u​l​d​ ​b​e​ ​r​e​n​a​m​e​d​ ​t​o​ ​{​t​o​}
			 * @param {unknown} to
			 */
			shouldRenameTo: RequiredParams<'to'>
			/**
			 * s​h​o​u​l​d​ ​b​e​ ​r​e​n​a​m​e​d​ ​t​o​ ​{​t​o​}​ ​(​t​a​r​g​e​t​ ​e​x​i​s​t​s​)
			 * @param {unknown} to
			 */
			targetExistsManual: RequiredParams<'to'>
			/**
			 * s​h​o​u​l​d​ ​b​e​ ​r​e​n​a​m​e​d​ ​(​c​a​n​n​o​t​ ​i​n​f​e​r​ ​t​a​r​g​e​t​)
			 */
			cannotInferTarget: string
		}
		inDirOnly: {
			/**
			 * d​i​r​e​c​t​o​r​y​ ​m​u​s​t​ ​e​x​i​s​t​ ​(​o​n​l​y​ ​{​o​n​l​y​}​)
			 * @param {unknown} only
			 */
			dirMustExist: RequiredParams<'only'>
			/**
			 * n​o​t​ ​i​n​ ​a​l​l​o​w​ ​l​i​s​t​ ​(​{​d​i​r​}​ ​a​l​l​o​w​s​ ​o​n​l​y​ ​{​o​n​l​y​}​)
			 * @param {unknown} dir
			 * @param {unknown} only
			 */
			forbiddenOnlyAllowed: RequiredParams<'dir' | 'only'>
			/**
			 * n​o​t​ ​i​n​ ​a​l​l​o​w​ ​l​i​s​t
			 */
			forbiddenTooMany: string
		}
		no: {
			/**
			 * h​i​t​ ​b​l​a​c​k​l​i​s​t​ ​(​{​n​a​m​e​}​)
			 * @param {unknown} name
			 */
			forbidden: RequiredParams<'name'>
		}
		has: {
			/**
			 * f​i​l​e​ ​n​o​t​ ​f​o​u​n​d​ ​(​r​e​q​u​i​r​e​d​:​ ​{​n​a​m​e​}​)
			 * @param {unknown} name
			 */
			mustExist: RequiredParams<'name'>
		}
		naming: {
			/**
			 * s​h​o​u​l​d​ ​b​e​ ​{​s​t​y​l​e​}
			 * @param {unknown} style
			 */
			invalid: RequiredParams<'style'>
			/**
			 * p​r​e​f​i​x​ ​s​h​o​u​l​d​ ​b​e​ ​{​p​a​t​t​e​r​n​}
			 * @param {unknown} pattern
			 */
			invalidPrefix: RequiredParams<'pattern'>
			/**
			 * s​u​f​f​i​x​ ​s​h​o​u​l​d​ ​b​e​ ​{​p​a​t​t​e​r​n​}
			 * @param {unknown} pattern
			 */
			invalidSuffix: RequiredParams<'pattern'>
		}
	}
	errors: {
		parser: {
			/**
			 * i​n​v​a​l​i​d​ ​w​h​e​r​e​ ​d​i​r​e​c​t​i​v​e
			 */
			invalidWhereDirective: string
			/**
			 * i​n​v​a​l​i​d​ ​p​a​t​h​ ​d​i​r​e​c​t​i​v​e
			 */
			invalidPathDirective: string
			/**
			 * {​r​u​l​e​}​ ​r​u​l​e​ ​f​o​r​m​a​t​ ​e​r​r​o​r​:​ ​{​l​i​n​e​}
			 * @param {unknown} line
			 * @param {unknown} rule
			 */
			ruleFormatError: RequiredParams<'line' | 'rule'>
			/**
			 * r​e​n​a​m​e​ ​m​i​s​s​i​n​g​ ​s​o​u​r​c​e​s​:​ ​{​l​i​n​e​}
			 * @param {unknown} line
			 */
			renameMissingSources: RequiredParams<'line'>
			/**
			 * u​n​k​n​o​w​n​ ​p​r​e​s​e​t​:​ ​{​n​a​m​e​}
			 * @param {unknown} name
			 */
			unknownPreset: RequiredParams<'name'>
			/**
			 * c​a​n​n​o​t​ ​p​a​r​s​e​ ​r​u​l​e​ ​l​i​n​e​:​ ​{​l​i​n​e​}
			 * @param {unknown} line
			 */
			cannotParseLine: RequiredParams<'line'>
		}
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * chous
		 */
		title: () => LocalizedString
		/**
		 * by
		 */
		by: () => LocalizedString
	}
	cli: {
		help: {
			/**
			 * Commands:
			 */
			commands: () => LocalizedString
			/**
			 * Create a new .chous rules file
			 */
			initCmdDesc: () => LocalizedString
			/**
			 * Install Cursor hooks for automatic linting
			 */
			installCursorHookDesc: () => LocalizedString
			/**
			 * Options:
			 */
			options: () => LocalizedString
			/**
			 * Set output language (default: auto)
			 */
			langHint: () => LocalizedString
			/**
			 * Show full filesystem tree (mode: verbose)
			 */
			verboseHint: () => LocalizedString
			/**
			 * Specify rules file (default: ./.chous)
			 */
			configHint: () => LocalizedString
			/**
			 * Enable strict mode for all directory-only rules
			 */
			strictHint: () => LocalizedString
			/**
			 * Output rule performance statistics to JSON file
			 */
			statsHint: () => LocalizedString
			/**
			 * Disable colored output
			 */
			noColorHint: () => LocalizedString
			/**
			 * Show help
			 */
			helpHint: () => LocalizedString
		}
		error: {
			/**
			 * Missing value for --lang (supported: {supported})
			 */
			missingLangValue: (arg: { supported: unknown }) => LocalizedString
			/**
			 * Unsupported language: {code} (supported: {supported})
			 */
			unsupportedLang: (arg: { code: unknown, supported: unknown }) => LocalizedString
			/**
			 * Missing value for --config
			 */
			missingConfigValue: () => LocalizedString
			/**
			 * Missing value for --stats-output
			 */
			missingStatsOutputValue: () => LocalizedString
			/**
			 * Unknown argument: {arg}
			 */
			unknownArg: (arg: { arg: unknown }) => LocalizedString
			/**
			 * Cannot read rules file: {path}
			 */
			cannotReadRulesFile: (arg: { path: unknown }) => LocalizedString
		}
		initCmd: {
			/**
			 * Created rules file
			 */
			created: () => LocalizedString
			/**
			 * Rules file already exists, skipped: {path}
			 */
			exists: (arg: { path: unknown }) => LocalizedString
			/**
			 * Detected framework: {name}
			 */
			detectedFramework: (arg: { name: unknown }) => LocalizedString
			/**
			 * Detected package manager: {name}
			 */
			detectedPackageManager: (arg: { name: unknown }) => LocalizedString
			/**
			 * Enabled presets: {names}
			 */
			enabledPresets: (arg: { names: unknown }) => LocalizedString
			/**
			 * Next: run chous
			 */
			nextStep: () => LocalizedString
			/**
			 * Cursor hooks installed
			 */
			cursorHooksInstalled: () => LocalizedString
			/**
			 * 💡 Tip: No .chous config file found. Auto-detected project type and used preset rules. Run `chous init` to create a config file for custom rules.
			 */
			suggestInit: () => LocalizedString
			/**
			 * 💡 Tip: Please read the `{configPath}` file to understand the specific rules (whitelist, blacklist, etc.), which will help you understand why these files don't meet the requirements and how to fix them.
			 */
			configHint: (arg: { configPath: unknown }) => LocalizedString
		}
	}
	meta: {
		/**
		 * Rules file: {path}
		 */
		rulesFile: (arg: { path: unknown }) => LocalizedString
		/**
		 * Imported rules: {path}
		 */
		importedRules: (arg: { path: unknown }) => LocalizedString
		/**
		 * Language: English
		 */
		lang: () => LocalizedString
		/**
		 * Mode: {mode}
		 */
		mode: (arg: { mode: unknown }) => LocalizedString
		/**
		 * Scanned {fileCount} files in {duration}ms
		 */
		performance: (arg: { duration: unknown, fileCount: unknown }) => LocalizedString
	}
	mode: {
		/**
		 * concise
		 */
		concise: () => LocalizedString
		/**
		 * verbose
		 */
		verbose: () => LocalizedString
	}
	report: {
		/**
		 * Found {count} issues
		 */
		foundIssues: (arg: { count: unknown }) => LocalizedString
		/**
		 * Found {count} issues (add `--verbose` flag for details)
		 */
		foundIssuesWithHint: (arg: { count: unknown }) => LocalizedString
		/**
		 * No issues found
		 */
		noIssues: () => LocalizedString
		/**
		 * →
		 */
		arrow: () => LocalizedString
		/**
		 * found required directory: {dir}
		 */
		foundRequiredDir: (arg: { dir: unknown }) => LocalizedString
		/**
		 * found required file: {name}
		 */
		foundRequiredFile: (arg: { name: unknown }) => LocalizedString
		/**
		 * missing required directory: {dir}
		 */
		missingRequiredDir: (arg: { dir: unknown }) => LocalizedString
		/**
		 * ...
		 */
		ellipsis: () => LocalizedString
		/**
		 * workspace: {root}
		 */
		workspace: (arg: { root: unknown }) => LocalizedString
		/**
		 * Whitelist
		 */
		whitelist: () => LocalizedString
		/**
		 * Blacklist
		 */
		blacklist: () => LocalizedString
		/**
		 * and {count} more items
		 */
		andMoreItems: (arg: { count: unknown }) => LocalizedString
	}
	issue: {
		move: {
			/**
			 * should be moved to {dir}
			 */
			shouldMoveToDir: (arg: { dir: unknown }) => LocalizedString
			/**
			 * required directory missing (for move {from} to {toDir})
			 */
			destDirMustExist: (arg: { from: unknown, toDir: unknown }) => LocalizedString
			/**
			 * target must be a directory (for move {from} to {toDir})
			 */
			destMustBeDir: (arg: { from: unknown, toDir: unknown }) => LocalizedString
			/**
			 * should be moved to {dir} (manual action required)
			 */
			unsafeManual: (arg: { dir: unknown }) => LocalizedString
		}
		thoseOnly: {
			/**
			 * not in allow list
			 */
			forbiddenOnlyAllowed: () => LocalizedString
			/**
			 * not in allow list
			 */
			forbiddenTooMany: () => LocalizedString
		}
		renameDir: {
			/**
			 * should be renamed to {to}
			 */
			shouldRenameTo: (arg: { to: unknown }) => LocalizedString
			/**
			 * should be migrated to {to} (target exists)
			 */
			shouldMigrateTo: (arg: { to: unknown }) => LocalizedString
			/**
			 * {dir} is empty and can be removed (target {to} exists)
			 */
			removeEmptyDir: (arg: { dir: unknown, to: unknown }) => LocalizedString
		}
		renameGlob: {
			/**
			 * should be renamed to {to}
			 */
			shouldRenameTo: (arg: { to: unknown }) => LocalizedString
			/**
			 * should be renamed to {to} (target exists)
			 */
			targetExistsManual: (arg: { to: unknown }) => LocalizedString
			/**
			 * should be renamed (cannot infer target)
			 */
			cannotInferTarget: () => LocalizedString
		}
		inDirOnly: {
			/**
			 * directory must exist (only {only})
			 */
			dirMustExist: (arg: { only: unknown }) => LocalizedString
			/**
			 * not in allow list ({dir} allows only {only})
			 */
			forbiddenOnlyAllowed: (arg: { dir: unknown, only: unknown }) => LocalizedString
			/**
			 * not in allow list
			 */
			forbiddenTooMany: () => LocalizedString
		}
		no: {
			/**
			 * hit blacklist ({name})
			 */
			forbidden: (arg: { name: unknown }) => LocalizedString
		}
		has: {
			/**
			 * file not found (required: {name})
			 */
			mustExist: (arg: { name: unknown }) => LocalizedString
		}
		naming: {
			/**
			 * should be {style}
			 */
			invalid: (arg: { style: unknown }) => LocalizedString
			/**
			 * prefix should be {pattern}
			 */
			invalidPrefix: (arg: { pattern: unknown }) => LocalizedString
			/**
			 * suffix should be {pattern}
			 */
			invalidSuffix: (arg: { pattern: unknown }) => LocalizedString
		}
	}
	errors: {
		parser: {
			/**
			 * invalid where directive
			 */
			invalidWhereDirective: () => LocalizedString
			/**
			 * invalid path directive
			 */
			invalidPathDirective: () => LocalizedString
			/**
			 * {rule} rule format error: {line}
			 */
			ruleFormatError: (arg: { line: unknown, rule: unknown }) => LocalizedString
			/**
			 * rename missing sources: {line}
			 */
			renameMissingSources: (arg: { line: unknown }) => LocalizedString
			/**
			 * unknown preset: {name}
			 */
			unknownPreset: (arg: { name: unknown }) => LocalizedString
			/**
			 * cannot parse rule line: {line}
			 */
			cannotParseLine: (arg: { line: unknown }) => LocalizedString
		}
	}
}

export type Formatters = {}
